{% set version = "0.11" %}

package:
  name: docstring-to-markdown
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/docstring-to-markdown/docstring-to-markdown-{{ version }}.tar.gz
  sha256: 5b1da2c89d9d0d09b955dec0ee111284ceadd302a938a03ed93f66e09134f9b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  skip: True  # [py<36]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - docstring_to_markdown
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/docstring-to-markdown
  summary: On the fly conversion of Python docstrings to markdown
  description: |
    On the fly conversion of Python docstrings to markdown.
    Currently can recognise reStructuredText and convert multiple of its features to Markdown.
    In the future will be able to convert Google docstrings too
  license: LGPL-2.1-or-later
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/docstring-to-markdown
  doc_url: https://github.com/python-lsp/docstring-to-markdown/blob/main/README.md

extra:
  recipe-maintainers:
    - bollwyvl
